version: '3.9'
services:
  app:
    build:
      context: .
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - '0.0.0.0:8000'
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '200k'
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  postgres_data:
