version: '3.9'
services:
  app:
    build:
      context: .
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - '0.0.0.0:8000'
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
    logging:
      driver: 'json-file'
      options:
        max-file: '10'
        max-size: '200k'
    volumes:
      - ./mysite/database:/app/database
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./mysite/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}